### PR TITLE
Use serde for json imports

### PR DESCRIPTION
**Pull request by tafia**
This is a first pull request to use `serde` crate instead of `from_json` (I know it is yours but given crates.io download it feels less standard than serde).

There is no intent of boosting performance, it is more some first _cleaning_ steps
- changed from_json to serde_json
- use `#[serde(default)]` instead of `Option<...>` in many places => i suppose it explains the change in benches
- add some basic (incomplete) tests for `format` module 

```
master
test animation ... bench:      11,335 ns/iter (+/- 2,458)
test loading   ... bench:   1,176,291 ns/iter (+/- 27,406)

serde
test animation ... bench:      10,452 ns/iter (+/- 1,377)
test loading   ... bench:   1,196,997 ns/iter (+/- 15,505)
```

It compiles and the rare tests are ok. Still I don't have proper tests so I suppose it is probably not good.
So don't merge, and only if you have time have a look.

### CODE REVIEW

**Comment by tomaka** [comment]
On one hand I really don't like the fact that the library requires nightly Rust. In fact that's why I haven't used serde when coding this lib. On the other hand I don't really like the `from_json` library either.

**Comment by tafia** [comment]
Yeah i don't like using nightly either.
At the same time I am at the very beginning of the changes so I prefer
using the latest and changing to stable once I think it is good enough.
You'd rather not use it for the moment.

**Comment by tafia** [comment]
I rewrote `calculate` to be more efficient (and easier to read I think):

```
test animation ... bench:       6,532 ns/iter (+/- 119)
test loading   ... bench:   1,225,161 ns/iter (+/- 23,513)
```

Some comments: 
- you seem not to use the `color`, is it intentional ?
- I cannot test it so I'm not even sure it outputs the expected results. Do you have a toy project I can test on ?

Next step: **bezier** calculations.
I've looked at the other runtimes and they store all the bezier curve calculations upfront. Do you think it is a valid approach or we must rather save some memory ?

**Comment by tafia** [comment]
Another naive question: why do you use `Matrix4` instead of `Matrix2` ?

**Comment by tomaka** [comment]
Please open multiple PRs instead of just one.

I'm using a Matrix4 because you will need to convert to a Matrix4 anyway to integrate with the rest of the scene. A Matrix3 could go as well. A Matrix2 wouldn't allow positionning.

**Comment by tafia** [comment]
> I'm using a Matrix4 because you will need to convert to a Matrix4 anyway to integrate with the rest of the scene. A Matrix3 could go as well. A Matrix2 wouldn't allow positionning.

Thanks for the answer, I'll try to see if there is any improvement using `Matrix3` first and converting to matrix 4 at the very end.

> Please open multiple PRs instead of just one.

Sure. I'll split but serde PR will be a prerequisite (the `format::` module has changed).
I've initially planned on working with bezier curve. I'll make it build on stable rust (with syntex crate) before.

I don't think it is a candidate for integration yet as I couldn't test it properly and I'll probably add some breaking changes in the future. You didn't answer my comments, in particular do you know any simple project that uses spine crate I can test on ?

**Comment by tomaka** [comment]
> do you know any simple project that uses spine crate I can test on ?

No. My game is closed source and its rendering process is too complex.

I know at least one other person on IRC that has written a renderer, but it's a long time ago and I don't remember their nickname.

**Comment by tafia** [comment]
I see. I'll add this to my todo list then. It could be a good exercise anyway (eg generating a gif file).
For the moment, I'll just try to return the exact same values as your master.

**Comment by tafia** [comment]
Closing as I've split this PR.
See #3 and #4.

**Pull request closed without merging**
