### PR TITLE
Serde stable

### PR DESCRIPTION
**Pull request by tafia**
This PR 
- extracts serde only changes from #2 (squashed)
- adds **stable rust** compatibility.
## stable / nightly

To compile on stable:

```
cargo build
```

To enable nightly-only features (better for development on deserialization, see [serde readme](https://github.com/serde-rs/serde#using-serde))

```
cargo build --no-default-features --features nightly
```
## ~~warning~~

~~Unfortunately, because of late change in `syntex_syntax` crate, **it doesn't compile for the moment**.
There is already a [fix from @sidred10](https://github.com/serde-rs/quasi/pull/11). I've tried it and  everything works perfectly.
I'll let you know once it has been merged.~~

### CODE REVIEW

**Comment by tafia** [comment]
The fix has just been merged!
I don't know how to force travis to try again ...

**Comment by tomaka** [comment]
The versions should not be `*`. Using `*` means that compilation can break at any time.

It's weird that there was a compilation error in a syntex crate. I'm a bit reluctant now because of that error. I want the compilation to never break.

**Comment by tafia** [comment]
Yes I agree, I was surprised too. I don't really know what we can do to prevent it except asking them not to use `*`. (spine also uses `*` by the way)

At the same time, I think serde is really used a lot so the support should be good enough in general ... probably better than some other crates currently used under the hood.

I don't know for the Cargo.lock file either. It feels to me it shouldn't be in .gitignore for the same reason ...

**Comment by tafia** [comment]
For what it worths they will be more careful in the future:
https://github.com/serde-rs/quasi/pull/11#issuecomment-143769215

**Comment by tomaka** [comment]
I tried this PR in my code:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SyntaxError(unknown field \"skeleton\", 1, 11)"', ../src/libcore\result.rs:736

**Comment by tomaka** [comment]
Content of the faulty file: http://pastebin.com/G2Leyf3k

This "skeleton" key isn't part of the official specs.
Apparently serde doesn't allow unknown keys :-/

**Comment by tafia** [comment]
That's very unfortunate! And they is no easy workaround.
I'm closing the PR as it won't be acceptable for the moment I think.

Anyway, the more I read about the other runtimes, the more I'm convinced I need to implement a wrapper over the json structs (to get the indexes etc ...). I've started doing this based on the serde implementation. I guess I'll switch to the current master instead and I hope it'll all be simpler.

I now have a good enough picture on what has to be done to render things quickly.

The journey to serde has been fun, I'll probably come back to it once the unknown keys are implemented.

Sorry for all this ...

**Comment by dtolnay** [comment]
@tafia @tomaka what is the status of this? Now that Serde is stable, standard, supports unknown keys, and is substantially faster (5-10x) than the version you tried, is this something that we should revisit?

**Comment by tafia** [comment]
It's been a long time I haven't work on it! I would be surprised it still compiles. 

I don't have much time atm and I'm no serde expert but feel free if you want to work on it.

**Pull request closed without merging**
